name: 🚀 Build and release

on:
    push:
        branches:
            - main
        paths:
            - pystrapi/**
            - pyproject.toml
            - .github/**

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - name: ⚙️ Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: 🔃 Checkout code
              uses: actions/checkout@v2

            - name: 📦 Install poetry
              run: pip install poetry

            # There is a bug in lazydocs so it's disabled ("relative import with no known parent package"):
            # - name: 📖 Generate docs
            #   run: |
            #       poetry install
            #       poetry run lazydocs --validate pystrapi --overview-file README.md
            # - name: ⬆️ Commit generated docs
            #   uses: EndBug/add-and-commit@v7
            #   with:
            #       add: docs
            #       message: "doc: update"
            #       committer_name: GitHub Actions
            #       committer_email: actions@github.com

            - name: 📢 Semantic Release
              uses: bjoluc/semantic-release-config-poetry@v1
              with:
                  pypi_token: ${{ secrets.PYPI_TOKEN }}
                  github_token: ${{ secrets.GITHUB_TOKEN }}
